// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ed5TX_Z6Na67cn3GuwLJkZo4HKqy2Wk',
    appId: '1:755301959068:web:948d92b79b7d0bf23e7459',
    messagingSenderId: '755301959068',
    projectId: 'dynamiclink-a6f79',
    authDomain: 'dynamiclink-a6f79.firebaseapp.com',
    storageBucket: 'dynamiclink-a6f79.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVTPJIiqTXTqW5hr7qxsNeRmr2U0zcmTs',
    appId: '1:755301959068:android:fec6ab7c2a0e45023e7459',
    messagingSenderId: '755301959068',
    projectId: 'dynamiclink-a6f79',
    storageBucket: 'dynamiclink-a6f79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOmRSgORMPRIPLjjpfkP3nX7t4t6m3LXw',
    appId: '1:755301959068:ios:efe21ae56effc8563e7459',
    messagingSenderId: '755301959068',
    projectId: 'dynamiclink-a6f79',
    storageBucket: 'dynamiclink-a6f79.appspot.com',
    iosBundleId: 'com.example.dynamicLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOmRSgORMPRIPLjjpfkP3nX7t4t6m3LXw',
    appId: '1:755301959068:ios:efe21ae56effc8563e7459',
    messagingSenderId: '755301959068',
    projectId: 'dynamiclink-a6f79',
    storageBucket: 'dynamiclink-a6f79.appspot.com',
    iosBundleId: 'com.example.dynamicLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4ed5TX_Z6Na67cn3GuwLJkZo4HKqy2Wk',
    appId: '1:755301959068:web:fbb601a8806710083e7459',
    messagingSenderId: '755301959068',
    projectId: 'dynamiclink-a6f79',
    authDomain: 'dynamiclink-a6f79.firebaseapp.com',
    storageBucket: 'dynamiclink-a6f79.appspot.com',
  );
}
