// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFX8bjuLCtKXeeu1ld1oDeXOf_ybUuT9Q',
    appId: '1:426298481437:web:fadb2e4bf4777f96399ff4',
    messagingSenderId: '426298481437',
    projectId: 'signin-8af1d',
    authDomain: 'signin-8af1d.firebaseapp.com',
    storageBucket: 'signin-8af1d.appspot.com',
    measurementId: 'G-CNFYVDERF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuvb-Yef3jL0osy9Uqa4v51iWmxiIUI6k',
    appId: '1:426298481437:android:03acff930b05c491399ff4',
    messagingSenderId: '426298481437',
    projectId: 'signin-8af1d',
    storageBucket: 'signin-8af1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjQGiT6TtlAlGC1hRLkwzrQaYurDyXm9M',
    appId: '1:426298481437:ios:ef37575b04697577399ff4',
    messagingSenderId: '426298481437',
    projectId: 'signin-8af1d',
    storageBucket: 'signin-8af1d.appspot.com',
    iosClientId: '426298481437-u5fcjl170ftk0s1iq179v384u1qvjl68.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjQGiT6TtlAlGC1hRLkwzrQaYurDyXm9M',
    appId: '1:426298481437:ios:ef37575b04697577399ff4',
    messagingSenderId: '426298481437',
    projectId: 'signin-8af1d',
    storageBucket: 'signin-8af1d.appspot.com',
    iosClientId: '426298481437-u5fcjl170ftk0s1iq179v384u1qvjl68.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFX8bjuLCtKXeeu1ld1oDeXOf_ybUuT9Q',
    appId: '1:426298481437:web:91b071c30b12922d399ff4',
    messagingSenderId: '426298481437',
    projectId: 'signin-8af1d',
    authDomain: 'signin-8af1d.firebaseapp.com',
    storageBucket: 'signin-8af1d.appspot.com',
    measurementId: 'G-3KH14TFKFZ',
  );
}
