// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGcdFSByFSo1a3wyY7j10RvFqIX3O6RbM',
    appId: '1:581122928396:web:e9574265fa8c6bf4092329',
    messagingSenderId: '581122928396',
    projectId: 'push-msg-e33b4',
    authDomain: 'push-msg-e33b4.firebaseapp.com',
    storageBucket: 'push-msg-e33b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHfOfgEfEyjj7DPw67H2f5BRl5pzmV8uc',
    appId: '1:581122928396:android:38cd0fc3e63e8100092329',
    messagingSenderId: '581122928396',
    projectId: 'push-msg-e33b4',
    storageBucket: 'push-msg-e33b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwBhADytsQJwKTk9yXranhHJslqi0TnGg',
    appId: '1:581122928396:ios:c5f35f409126dc9a092329',
    messagingSenderId: '581122928396',
    projectId: 'push-msg-e33b4',
    storageBucket: 'push-msg-e33b4.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwBhADytsQJwKTk9yXranhHJslqi0TnGg',
    appId: '1:581122928396:ios:c5f35f409126dc9a092329',
    messagingSenderId: '581122928396',
    projectId: 'push-msg-e33b4',
    storageBucket: 'push-msg-e33b4.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGcdFSByFSo1a3wyY7j10RvFqIX3O6RbM',
    appId: '1:581122928396:web:9b8cf8f0e0a6dc23092329',
    messagingSenderId: '581122928396',
    projectId: 'push-msg-e33b4',
    authDomain: 'push-msg-e33b4.firebaseapp.com',
    storageBucket: 'push-msg-e33b4.appspot.com',
  );
}
